### ISSUE TITLE
Can you make this in English please 

### ISSUE THREAD

**Issue by aarvndhNG** [chi-rei-den/POBC.Task#1]

**Comment by Cybeta** [comment]
Or you can directly change the source text to English.


---Original---
From: "That ***@***.***&gt;
Date: Wed, Jan 4, 2023 19:00 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [chi-rei-den/POBC.Task] Can you make this in English please (Issue #1)




 
Closed #1 as completed.
